name: Build and Publish overpass-api

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate Dockerfiles
        run: python update.py

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Overpass 0.7.62
        uses: docker/build-push-action@v6
        with:
          context: ./0.7.62
          file: ./0.7.62/Dockerfile
          push: true
          tags: |
            ghcr.io/dubsof/overpass-api:0.7.62
            ghcr.io/dubsof/overpass-api:latest
